version: '3.8'
services:
  backend:
    build: https://github.com/CSC7437-Msc-CSN-M2-GlobalLabs-2023-2024/backend.git
    container_name: "backend"
    image: backend
    ports:
      - "8080:8080"
    networks:
        - public_net
    depends_on:
        - mydatabase
#docker run --name mydatabase  -d -p 3306:3306 mysql:latest
  mydatabase:
    image: mysql:latest
    container_name: "mydatabase"
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_USER: myuser
        MYSQL_PASSWORD: secret
        MYSQL_DATABASE: mydatabase
        #MYSQL_ALLOW_EMPTY_PASSWORD: yes
    networks:
        - public_net
    ports:
        - "3306:3306"

networks:
    public_net:
        driver: bridge
